import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Home from "@/components/Home";
import About from "@/components/About";
import Features from "@/components/Features";
import Work from "@/components/Work";
import Pricing from "@/components/Pricing";
import Testonomial from "@/components/Testonomial";
import Get from "@/components/Footer";
import "@fortawesome/fontawesome-svg-core/styles.css"; // import Font Awesome CSS

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <Navbar/>
        <Home/>
        <About/>
        <Features/>
        <Work/>
        <Pricing/>
        <Testonomial/>
        <Get/>

        {children}
      </body>
    </html>
  );
}
